added options for: colors, hiding, sha1 length, orientation, git dir

diff --git a/git-draw b/git-draw
--- a/git-draw
+++ b/git-draw
@@ -26,9 +26,9 @@
 #   2) dot (see graphviz) is called to produce an image out of that .dot file.
 #   3) display (see imagemagick) is called to display that image.
 #
-#   Because git-draw currently is quite dumb, the current working directory
-#   must be at the root of the working tree of your project, i.e. the
-#   directory which contains the .git directory.
+#   As long as you run git-draw from within a git repository, it will graph
+#   the repository.   An alternate git repository can be chosen using the 
+#   --git-dir and/or --work-dir flags.
 #
 #   The intention is to help learning Git's basic concepts (references, Git
 #   objects, SHA-1 checksum over content as id). Virtually all information
@@ -38,6 +38,9 @@
 #   references aka pointers and graphs.
 #
 # OPTIONS
+#   -h, --help
+#     Prints a help message and exits.
+#
 #   -p, --print-only
 #     Only prints the .dot file to STDOUT. Mutually exclusive with
 #     --image-only.
@@ -46,8 +49,82 @@
 #     Only generates an image of the graph, and a .dot file beforehand.
 #     Mutually exclusive with --print-only.
 #
+#   -g, --git-dir
+#     Git repository directory to use
+#
+#   -w, --work-dir    
+#     Top level git working directory
+#
+#   --image-filename <filename>
+#     Name of the image file to generate
+#
+#   --dot-filename <filename>
+#     Name of the dot file to generate
+#
+#   --display-cmd <command>
+#     Command to use to display image
+#
+#   --sha1-length <length>
+#     Number of sha1 characters to display in the graph
+#  
+#   --hide-legend
+#     Don't display the legend
+#
+#   --hide-objects
+#     Don't display git objects
+#
+#   --hide-commitcontent
+#     Hide commit content
+#
+#   --hide-tagcontent
+#     Hide tag content
+#
+#   --hide-treecontent
+#     Hide tree content
+#
+#   --hide-blobcontent
+#     Hide blob content
+#
+#   --hide-refs
+#     Don't display references
+#
+#   --hide-reflogs
+#     Don't display reflogs
+#
+#   --hide-index
+#     Don't display the index
+#
+#   --color-scheme <color scheme>
+#     Choose color scheme
+#        <color scheme> can be one of: set312, spectral11, blues9, brbg11
+#                                      bupu9, dark28, paired12, pastel19, set19
+#
+#   --color-commit <color>
+#     Set color for commit objects
+#
+#   --color-tag <color>
+#     Set color for tag objects
+#
+#   --color-tree <color>
+#     Set color for tree objects 
+#
+#   --color-blob <color>
+#     Set color for blob objects
+#
+#   --color-default <color>
+#     Set default color
+#
+#   --orientation <orientation>
+#     Change the layout orientation of the graph.   Must be one 
+#     of the following:
+#         TB      top to bottom, the default
+#         BT      bottom to top
+#         LR      left to right
+#         RL      right to left
+#
 # AUTHOR
 #   Written by Florian Kaufmann <sensorflo@gmail.com>
+#   Modifications by Nathan Doss <nathan.doss@gmail.com>
 #
 # COPYRIGHT
 #   Florian Kaufmann 2014. License GPLv3+: GNU GPL version 3 or later
@@ -58,15 +135,130 @@
 # SEE ALSO
 #   git(1)
 
+# define color schemes
+color_scheme_set312_commit="/set312/7"
+color_scheme_set312_tree="/set312/6"
+color_scheme_set312_blob="/set312/3"
+color_scheme_set312_tag="/set312/12"
+color_scheme_set312_default="white"
+
+color_scheme_spectral11_commit="/spectral11/8"
+color_scheme_spectral11_tree="/spectral11/4"
+color_scheme_spectral11_blob="/spectral11/10"
+color_scheme_spectral11_tag="/spectral11/5"
+color_scheme_spectral11_default="white"
+
+color_scheme_blues9_commit="/blues9/3"
+color_scheme_blues9_tree="/blues9/5"
+color_scheme_blues9_blob="/blues9/7"
+color_scheme_blues9_tag="/blues9/2"
+color_scheme_blues9_default="white"
+
+color_scheme_brbg11_commit="/brbg11/3"
+color_scheme_brbg11_tree="/brbg11/5"
+color_scheme_brbg11_blob="/brbg11/7"
+color_scheme_brbg11_tag="/brbg11/9"
+color_scheme_brbg11_default="white"
+
+color_scheme_bupu9_commit="/bupu9/2"
+color_scheme_bupu9_tree="/bupu9/4"
+color_scheme_bupu9_blob="/bupu9/6"
+color_scheme_bupu9_tag="/bupu9/8"
+color_scheme_bupu9_default="white"
+
+color_scheme_dark28_commit="/dark28/5"
+color_scheme_dark28_tree="/dark28/2"
+color_scheme_dark28_blob="/dark28/3"
+color_scheme_dark28_tag="/dark28/6"
+color_scheme_dark28_default="white"
+
+color_scheme_paired12_commit="/paired12/3"
+color_scheme_paired12_tree="/paired12/1"
+color_scheme_paired12_blob="/paired12/7"
+color_scheme_paired12_tag="/paired12/11"
+color_scheme_paired12_default="white"
+
+color_scheme_pastel19_commit="/pastel19/3"
+color_scheme_pastel19_tree="/pastel19/5"
+color_scheme_pastel19_blob="/pastel19/4"
+color_scheme_pastel19_tag="/pastel19/6"
+color_scheme_pastel19_default="white"
+
+color_scheme_set19_commit="/set19/3"
+color_scheme_set19_tree="/set19/5"
+color_scheme_set19_blob="/set19/2"
+color_scheme_set19_tag="/set19/6"
+color_scheme_set19_default="white"
+
+# set defaults
+dotfilename=git-draw.dot
+imgfilename=git-draw.png
+displaycmd=display
+sha1length=4
+showlegend=1
+showobjects=1
+showcommits=1
+showtrees=1
+showtags=1
+showblobs=1
+showcommitcontent=1
+showtreecontent=1
+showtagcontent=1
+showblobcontent=1
+showrefs=1
+showreflogs=1
+showindex=1
+orientation="TB"
+export GIT_DIR=$(git rev-parse --git-dir)
+export GIT_WORK_TREE=$(git rev-parse --show-toplevel)
+colorscheme="set312"
+
+# set colors (hack ... got to be a better way)
+color_commit=$(eval "echo \${color_scheme_${colorscheme}_commit}")
+color_tag=$(eval "echo \${color_scheme_${colorscheme}_tag}")
+color_tree=$(eval "echo \${color_scheme_${colorscheme}_tree}")
+color_blob=$(eval "echo \${color_scheme_${colorscheme}_blob}")
+color_default=$(eval "echo \${color_scheme_${colorscheme}_default}")
+
 # $1 = exit code
 print_usage_and_exit() {
   cat <<EOF
-Usage: git-draw [--help] [-p|--print-only] [-i|--image-only]"
-  -p|--print-only  Only print .dot to stdout."
-  -i|--image-only  Only create an image, and a .dot file beforehand."
+Usage: git-draw [options]
+  -h | --help                         Print help message & exit
+  -p | --print-only                   Only print .dot to stdout.
+  -i | --image-only                   Only create an image, and a .dot file beforehand.
+  -g | --git-dir                      Git repository directory to use [$GIT_DIR]
+  -w | --work-dir                     Top level git working directory [$GIT_WORK_TREE]
+       --image-filename <filename>    Name of the image file to generate [$imgfilename]
+       --dot-filename <filename>      Name of the dot file to generate [$dotfilename]
+       --display-cmd <command>        Command to use to display image [$displaycmd]
+       --sha1-length <length>         Number of sha1 characters to display [$sha1length]
+       --hide-legend                  Don't display the legend
+       --hide-objects                 Don't display git objects
+       --hide-commitcontent           Don't display commit content
+       --hide-tagcontent              Don't display tag content
+       --hide-treecontent             Don't display tree content
+       --hide-blobcontent             Don't display blob content
+       --hide-refs                    Don't display references
+       --hide-reflogs                 Don't display reflogs
+       --hide-index                   Don't display the index
+       --color-scheme <color scheme>  Choose color scheme.  Can be one of the following:
+                                            set312, spectral11, blues9, brbg11
+                                            bupu9, dark28, paired12, pastel19, set19
+       --color-commit <color>         Set color for commit objects
+       --color-tag <color>            Set color for tag objects
+       --color-tree <color>           Set color for tree objects 
+       --color-blob <color>           Set color for blob objects
+       --color-default <color>        Set default color
+       --orientation <orientation>    Change the graph orientation [default=$orientation] 
+                                      <orientation> must be one of the following:
+                                         TB      top to bottom, the default
+                                         BT      bottom to top
+                                         LR      left to right
+                                         RL      right to left
 
 The primary documentation is at the top of the git-draw script itself, see
-$(type -p git-draw)
+$0
 EOF
   exit $1
 }
@@ -85,34 +277,43 @@ EOF
 #      'type=' and 'id=' to be very clear. Optionally turn off with options.
 #   -  add a graph title / caption which tells the git command(s) since the
 #      last version of the repository content.
+#   -  Read gitrepository-layou(1) to find out more things which could be
+#      displayed
+#   -  Draw multiple repos in one image. Usefull to demonstrate distributed git.
+#   -  Draw packed objects and refs in a subgraph respectively.
+#   -  Make option handling more robust
+
+# DONE
 #   -  Provide options to choose the tool to display the image outputted by
 #      dot.
+#   -  Allow that the current working directory can be any subdirectory of a
+#      git project. Similarly, allow to specify the git repository via command
+#      line arguments.
+#   -  Add option to watch git directory & update image if it changes
+#   -  Add option to specify display length of sha1 hashes
+#   -  Add options to specify output filenames
+#   -  Color schemes
+#   -  Option for colors of each object
+#   -  Options to hide object contents
 #   -  Support for all those possible other layouts of git repositories. Bare
 #      repository, a .git file at the root pointing to the real directory,
 #      environment variables etc. Most probably by using git commands
 #      exclusive opposed to directly access files within .git, or by asking
 #      git for the path to the repository.
-#   -  Read gitrepository-layou(1) to find out more things which could be
-#      displayed
-#   -  Draw multiple repos in one image. Usefull to demonstrate distributed git.
-#   -  Draw packed objects and refs in a subgraph respectively.
-#   -  Allow that the current working directory can be any subdirectory of a
-#      git project. Similarly, allow to specify the git repository via command
-#      line arguments.
 
 abbreviate_sha1() {
   # BUG: in a blob or commit-msg, would also replace what looks like a sha1
-  perl -pe 's/([0-9a-f]{40})/substr(`git rev-parse --short=4 $1`,0,-1)/eg'
+  perl -pe 's/([0-9a-f]{40})/substr(`git rev-parse --short='$sha1length' $1`,0,-1)/eg'
 }
 
 ls_all_objects() {
   # unpacked objects
-  find .git/objects/ -type f |
+  find $GIT_DIR/objects/ -type f |
     perl -ne 'print "$1$2\n" if m@^.*/([a-f0-9]{2})/([a-f0-9]{38})@' 
 
   # packed objects
   # note that the .idx is not always present
-  find .git/objects/pack/ -iname '*.idx' | while read idxfile; do
+  find $GIT_DIR/objects/pack/ -iname '*.idx' | while read idxfile; do
     cat $idxfile | git show-index |
       perl -pe 's@^.*?([a-f0-9]{40}).*$@$1@'
   done
@@ -120,11 +321,11 @@ ls_all_objects() {
 
 ls_all_refs() {
   # todo: refs like MERGE_HEAD are still not printed
-  git show-ref --abbrev=4
-  cat .git/HEAD | perl -ne '
+  git show-ref --abbrev=$sha1length
+  cat $GIT_DIR/HEAD | perl -ne '
     m/^(?:ref: )?(.*?)$/;
     if ($1 =~ m/([a-f0-9]{40})/) {
-      $idshort = substr(`git rev-parse --short=4 $1`,0,-1);
+      $idshort = substr(`git rev-parse --short='$sha1length' $1`,0,-1);
     }
     else { $idshort = $1 }
     print $idshort . " HEAD\n";'
@@ -132,7 +333,7 @@ ls_all_refs() {
 
 ls_all_objects_short() {
   ls_all_objects | while read sha1; do
-    git rev-parse --short=4 $sha1
+    git rev-parse --short=$sha1length $sha1
   done
 }
 
@@ -142,12 +343,42 @@ print_dot_objects() {
     object_type=$(git cat-file -t $id)
     objcontent=$(git cat-file -p $id | abbreviate_sha1 |
       perl -pe 's/([^a-zA-Z0-9\n\r])/\\$1/g; s/(\r?\n)?$/\\l/;')
+
     case $object_type in
-      commit) fillcolor=palegreen1;;
-      tag)    fillcolor=lightyellow;;  
-      *)      fillcolor=white;;
+      commit) 
+            fillcolor="$color_commit"
+            if [ $showcommitcontent != 1 ]; then
+                objcontent=""
+            fi
+            ;; 
+
+      tag)    
+            fillcolor="$color_tag"
+            if [ $showtagcontent != 1 ]; then
+                objcontent=""
+            fi
+            ;; 
+
+      tree)  
+            fillcolor="$color_tree"
+            if [ $showtreecontent != 1 ]; then
+                objcontent=""
+            fi
+            ;; 
+
+      blob) 
+            fillcolor="$color_blob"
+            if [ $showblobcontent != 1 ]; then
+                objcontent=""
+            fi
+            ;; 
+
+      *)      
+            fillcolor="$color_default"
+            ;;
     esac
-    echo "  $dotid [fillcolor=$fillcolor, style=\"filled,rounded\", "\
+
+    echo "  $dotid [fillcolor=\"$fillcolor\", style=\"filled,rounded\", "\
       "label=\"{{obj:$object_type|$id}|$objcontent}\"]"
 
     # todo: use git's commands to extract the object references
@@ -157,11 +388,11 @@ print_dot_objects() {
     #   replace what looks like a sha1
     git cat-file -p $id |
       perl -ne 'print "  '$dotid' -> _" .
-        `git rev-parse --short=4 $1` if /([a-f0-9]{40})/'
+        `git rev-parse --short='$sha1length' $1` if /([a-f0-9]{40})/'
   done
 
   git fsck --cache --unreachable --dangling 2>/dev/null |
-   perl -ne 'print "  _" . substr(`git rev-parse --short=4 $1`,0,-1) .
+   perl -ne 'print "  _" . substr(`git rev-parse --short='$sha1length' $1`,0,-1) .
      " [style=dotted]\n" if /^(?:dangling|unreachable)\b.*?([a-f0-9]{40})/'
 }
 
@@ -228,7 +459,7 @@ print_dot_references() {
 
 print_dot_ref_logs() {
   firstiter="non-empty-string" # i.e. true
-  git show-ref --abbrev=4 |
+  git show-ref --abbrev=$sha1length |
     # The following code depends upon HEAD being the last in the list
     perl -pe 's@^.*?(\brefs/\S*)$@$1@; END { print "HEAD\n";}' |
     while read refname; do
@@ -245,7 +476,7 @@ print_dot_ref_logs() {
           
           if (m/^([a-f0-9]+).*@\{\d+\}: (.*?)$/) { $id_any=$1; $msg=$2; }
           elsif (m/^([a-f0-9]+)/) { $id_any=$1; $msg="<lastentry>"; }
-          $id_short = substr(`git rev-parse --short=4 $id_any`,0,-1);
+          $id_short = substr(`git rev-parse --short='$sha1length' $id_any`,0,-1);
           print "  $dotid_reflog -> _$id_short [color=gray90]\n";
           
           s/^[a-f0-9]+//;            # strip sha1; $id_short will be used instead
@@ -265,7 +496,7 @@ print_dot_ref_logs() {
 }
 
 print_dot_index() {
-  git ls-files --stage --abbrev=4 | perl -ne '
+  git ls-files --stage --abbrev=$sha1length | perl -ne '
     if (/^[0-9]+\s+([a-f0-9]+)/) {
       print "  index -> _$1\n";
 
@@ -284,37 +515,184 @@ print_dot_index() {
 print_dot() { 
   echo "digraph structs {"
   echo "  node [shape=record,fontsize=11];"
-  echo "  subgraph cluster_0 {"
-  echo "    color=gray80;"
-  echo "    label = \"legend\\l\";"
-  echo "    legend_node [label=\"{{type:subtype|id/name}|content\\l|metadata from config\\l}\"]"
-  echo "  }"
+  echo "  rankdir=\"$orientation\";"
 
-  print_dot_objects
-  print_dot_references
-  print_dot_ref_logs
-  print_dot_index
+  if [ $showlegend = 1 ]; then
+      echo "  subgraph cluster_0 {"
+      echo "    color=gray80;"
+      echo "    label = \"legend\\l\";"
+      echo "    legend_node [label=\"{{type:subtype|id/name}|content\\l|metadata from config\\l}\"]"
+      echo "  }"
+  fi
+
+  if [ $showobjects = 1 ]; then 
+      print_dot_objects 
+  fi
+
+  if [ $showrefs = 1 ]; then 
+      print_dot_references
+  fi
+
+  if [ $showreflogs = 1 ]; then
+      print_dot_ref_logs
+  fi
+
+  if [ $showindex = 1 ]; then
+      print_dot_index
+  fi
+
   echo "}"
 }
 
 # process options
-dotfilename=git-draw.dot
-imgfilename=git-draw.png
-if [ $# = 0 ]; then
-  :
-elif [ \( $# = 1 \) -a \( "$1" = "-p" -o "$1" = "--print-only" \) ] ; then
-  print_only=1
-elif [ \( $# = 1 \) -a \( "$1" = "-i" -o "$1" = "--image-only" \) ] ; then
-  image_only=1
-elif [ \( $# = 1 \) -a \( "$1" = "--help" \) ] ; then
-  print_usage_and_exit 0
-else
-  echo "Invalid options" >&2
-  print_usage_and_exit 1 >&2
+while test $# -gt 0
+do
+  case $1 in
+
+    -h | --help)
+      print_usage_and_exit 0
+      ;;
+
+    -p | --print-only)
+      print_only=1
+      ;;
+
+    -i | --image-only)
+      image_only=1
+      ;;
+
+    -g | --git-dir)
+      GIT_DIR=$2
+      shift
+      ;;
+
+    -w | --work-dir)
+      GIT_WORK_TREE=$2
+      shift
+      ;;
+
+    --dot-filename)
+      dotfilename=$2
+      shift
+      ;;
+
+    --display-cmd)
+      displaycmd=$2
+      shift
+      ;;
+
+    --sha1-length)
+      sha1length=$2
+      shift
+      ;;
+
+    --hide-legend)
+      showlegend=0
+      ;;
+
+    --hide-objects)
+      showobjects=0
+      ;;
+
+    --hide-commitcontent)
+      showcommitcontent=0
+      ;;
+
+    --hide-tagcontent)
+      showtagcontent=0
+      ;;
+
+    --hide-treecontent)
+      showtreecontent=0
+      ;;
+
+    --hide-blobcontent)
+      showblobcontent=0
+      ;;
+
+    --hide-refs)
+      showrefs=0
+      ;;
+
+    --hide-reflogs)
+      showreflogs=0
+      ;;
+
+    --hide-index)
+      showindex=0
+      ;;
+
+    --color-scheme)
+      colorscheme=$2
+      color_commit=$(eval "echo \${color_scheme_${colorscheme}_commit}")
+      color_tag=$(eval "echo \${color_scheme_${colorscheme}_tag}")
+      color_tree=$(eval "echo \${color_scheme_${colorscheme}_tree}")
+      color_blob=$(eval "echo \${color_scheme_${colorscheme}_blob}")
+      color_default=$(eval "echo \${color_scheme_${colorscheme}_default}")
+      shift
+      ;;
+
+    --color-commit)
+      color_commit=$2
+      shift
+      ;;
+
+    --color-tag)
+      color_tag=$2
+      shift
+      ;;
+
+    --color-tree)
+      color_tree=$2
+      shift
+      ;;
+
+    --color-blob)
+      color_blob=$2
+      shift
+      ;;
+
+    --color-default)
+      color_default=$2
+      shift
+      ;;
+
+    --orientation)
+      orientation=$2
+      shift
+      ;;
+
+    --* | -?)
+      echo "ERROR: unknown option ($1)";
+      print_usage_and_exit 1 >&2
+      ;;
+
+    # Split apart combined short options
+    -*)
+      split=$1
+      shift
+      set -- $(echo "$split" | cut -c 2- | sed 's/./-& /g') "$@"
+      continue
+      ;;
+
+    # Done with options
+    *)
+      break
+      ;;
+  esac
+
+  shift
+done
+
+# check that image_only & print_only aren't both selected
+if [ "$image_only" -a "$print_only" ]; then
+    echo "ERROR: --image_only and --print_only are mutualy exclusive options"
+    print_usage_and_exit 1 >&2
 fi
 
+
 # check preconditions
-if [ ! -d .git ]; then
+if [ ! -d $GIT_DIR/objects ]; then
   echo "Not a git repository" >&2
   exit 1
 fi
@@ -348,14 +726,17 @@ dot -Tpng "$dotfilename" > "$imgfilename" || exit 1
 if [ "$image_only" = 1 ] ; then
   exit 0
 fi
-if ! which display >&2 >/dev/null; then
-  cat >&2 <<EOF
+
+if [ "$displaycmd" = "display" ]; then
+    if ! which display >&2 >/dev/null; then
+        cat >&2 <<EOF
 display (part of imagemagick) not found. Image '$imgfilename' was generated,
 but I cannot display it. Either use the --image-only option, or install
 imagemagick. If you have apt-get, you can do that with 'sudo apt-get install
 imagemagick'.
 EOF
-  exit 1
+        exit 1
+    fi
 fi
-display "$imgfilename"
+$displaycmd "$imgfilename"
 
